<h2>My Uploads</h2>
<a href="<?php echo $this->url(NULL,array('controller'=>'UploadManager','action'=>'upload'));?>">upload new file</a>
<table class="table">
    <tr>
        <th>Label</th>
        <th>Filename</th>
        
        <th>Actions</th>
    </tr>
    <?php foreach ($myUploads as $upload): ?>
        <tr>
            <td><?php echo $this->escapeHtml($upload->label);?></td>
            <td><?php echo $this->escapeHtml($upload->filename);?></td>
            
            <td>
                
                <a href="<?php echo $this->url('users/upload-manager', 
                        array('action' => 'delete', 'id' => $upload->id));?>" onclick="return confirm('Are you sure?')">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>